### ISSUE TITLE
TypeError: Cannot read property of 'TOP' of undefined

### ISSUE THREAD

**Issue by bansan699** [Vencord/Installer#20] opened 2023-03-01 20:19 UTC
Unable to open any kind of settings. Installed both vencord and asar.

at Z1 (VencordRenderer:70:7106) 
at Sa (3ceSa3a3ee1992708511.js:1654:54) 
at yu (3ce5a3a3ee1992708511.js:1708:146) at Oc (3ceSa3a3ee1992708511.js:1701:89) 
at Ic (3ceSa3a3ee1992708511.js:1701:17) at he (3ce5a3a3ee1992708511.js:1700:867) 
at is (3ce5a3a3ee1992708511.js:1697:642) at uc (3ceSa3a3ee1992708511.js:1698:49) 
at Fo (3ce5a3a3ee1992708511.js:1637:577) at 3ce5a3a3ee1992708511.js:1695:555

**Comment by lewisakura** [comment] 2023-03-01 20:21
duplicate of https://github.com/Vendicated/Vencord/issues/549, why did you open it here though?

**Closed** 2023-03-01 20:27 UTC
